---
# see https://docs.mergify.com/

pull_request_rules:
  - name: "Enqueue approved PRs"
    conditions:
      # those rules are implicit for the queue action:
      # - "-draft"
      # - "-mergify-configuration-changed"
      # - check-success=XXX
      - "-closed"
      - "-conflict"
      - "-locked"
      - "-merged"
      - "base = main"
      - "label != 'no ci'"
    actions:
      queue:
        method: squash
        # commit_message_template: "{{ body | get_section('## Commit Message') }}"

  - name: "Add comment"
    conditions:
      - "label = 'test'"
    actions:
      comment:
        message: "Test comment"

  - name: "Assign PRs"
    conditions:
      - "-closed"
      - "#assignee = 0"
    actions:
      assign:
        add_users: ["{{ author }}"]

  - name: "Unassign PRs"
    conditions:
      - "closed"
      - "#assignee > 0"
    actions:
      assign:
        remove_users: {{ assignee }}

queue_rules:
  - name: default
    merge_conditions: [] # we rely on GitHub's branch protection rules
