---
name: Wait
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  wait:
    name: wait
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'no ci')

    steps:
      - run: sleep 10
